// Autogenerated from Pigeon (v9.2.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "PlaybackPlatformApi.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface NpawConfig ()
+ (NpawConfig *)fromList:(NSArray *)list;
+ (nullable NpawConfig *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface AppConfig ()
+ (AppConfig *)fromList:(NSArray *)list;
+ (nullable AppConfig *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface MediaItem ()
+ (MediaItem *)fromList:(NSArray *)list;
+ (nullable MediaItem *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface MediaMetadata ()
+ (MediaMetadata *)fromList:(NSArray *)list;
+ (nullable MediaMetadata *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PlayerStateSnapshot ()
+ (PlayerStateSnapshot *)fromList:(NSArray *)list;
+ (nullable PlayerStateSnapshot *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface ChromecastState ()
+ (ChromecastState *)fromList:(NSArray *)list;
+ (nullable ChromecastState *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PlayerTracksSnapshot ()
+ (PlayerTracksSnapshot *)fromList:(NSArray *)list;
+ (nullable PlayerTracksSnapshot *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface Track ()
+ (Track *)fromList:(NSArray *)list;
+ (nullable Track *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PrimaryPlayerChangedEvent ()
+ (PrimaryPlayerChangedEvent *)fromList:(NSArray *)list;
+ (nullable PrimaryPlayerChangedEvent *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PlayerStateUpdateEvent ()
+ (PlayerStateUpdateEvent *)fromList:(NSArray *)list;
+ (nullable PlayerStateUpdateEvent *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PositionDiscontinuityEvent ()
+ (PositionDiscontinuityEvent *)fromList:(NSArray *)list;
+ (nullable PositionDiscontinuityEvent *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PlaybackStateChangedEvent ()
+ (PlaybackStateChangedEvent *)fromList:(NSArray *)list;
+ (nullable PlaybackStateChangedEvent *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PlaybackEndedEvent ()
+ (PlaybackEndedEvent *)fromList:(NSArray *)list;
+ (nullable PlaybackEndedEvent *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface PictureInPictureModeChangedEvent ()
+ (PictureInPictureModeChangedEvent *)fromList:(NSArray *)list;
+ (nullable PictureInPictureModeChangedEvent *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface MediaItemTransitionEvent ()
+ (MediaItemTransitionEvent *)fromList:(NSArray *)list;
+ (nullable MediaItemTransitionEvent *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation NpawConfig
+ (instancetype)makeWithAppName:(nullable NSString *)appName
    appReleaseVersion:(nullable NSString *)appReleaseVersion
    accountCode:(nullable NSString *)accountCode
    deviceIsAnonymous:(nullable NSNumber *)deviceIsAnonymous {
  NpawConfig* pigeonResult = [[NpawConfig alloc] init];
  pigeonResult.appName = appName;
  pigeonResult.appReleaseVersion = appReleaseVersion;
  pigeonResult.accountCode = accountCode;
  pigeonResult.deviceIsAnonymous = deviceIsAnonymous;
  return pigeonResult;
}
+ (NpawConfig *)fromList:(NSArray *)list {
  NpawConfig *pigeonResult = [[NpawConfig alloc] init];
  pigeonResult.appName = GetNullableObjectAtIndex(list, 0);
  pigeonResult.appReleaseVersion = GetNullableObjectAtIndex(list, 1);
  pigeonResult.accountCode = GetNullableObjectAtIndex(list, 2);
  pigeonResult.deviceIsAnonymous = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable NpawConfig *)nullableFromList:(NSArray *)list {
  return (list) ? [NpawConfig fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.appName ?: [NSNull null]),
    (self.appReleaseVersion ?: [NSNull null]),
    (self.accountCode ?: [NSNull null]),
    (self.deviceIsAnonymous ?: [NSNull null]),
  ];
}
@end

@implementation AppConfig
+ (instancetype)makeWithAppLanguage:(nullable NSString *)appLanguage
    audioLanguage:(nullable NSString *)audioLanguage
    subtitleLanguage:(nullable NSString *)subtitleLanguage
    analyticsId:(nullable NSString *)analyticsId
    sessionId:(nullable NSNumber *)sessionId {
  AppConfig* pigeonResult = [[AppConfig alloc] init];
  pigeonResult.appLanguage = appLanguage;
  pigeonResult.audioLanguage = audioLanguage;
  pigeonResult.subtitleLanguage = subtitleLanguage;
  pigeonResult.analyticsId = analyticsId;
  pigeonResult.sessionId = sessionId;
  return pigeonResult;
}
+ (AppConfig *)fromList:(NSArray *)list {
  AppConfig *pigeonResult = [[AppConfig alloc] init];
  pigeonResult.appLanguage = GetNullableObjectAtIndex(list, 0);
  pigeonResult.audioLanguage = GetNullableObjectAtIndex(list, 1);
  pigeonResult.subtitleLanguage = GetNullableObjectAtIndex(list, 2);
  pigeonResult.analyticsId = GetNullableObjectAtIndex(list, 3);
  pigeonResult.sessionId = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable AppConfig *)nullableFromList:(NSArray *)list {
  return (list) ? [AppConfig fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.appLanguage ?: [NSNull null]),
    (self.audioLanguage ?: [NSNull null]),
    (self.subtitleLanguage ?: [NSNull null]),
    (self.analyticsId ?: [NSNull null]),
    (self.sessionId ?: [NSNull null]),
  ];
}
@end

@implementation MediaItem
+ (instancetype)makeWithUrl:(nullable NSString *)url
    mimeType:(nullable NSString *)mimeType
    metadata:(nullable MediaMetadata *)metadata
    isLive:(nullable NSNumber *)isLive
    playbackStartPositionMs:(nullable NSNumber *)playbackStartPositionMs
    lastKnownAudioLanguage:(nullable NSString *)lastKnownAudioLanguage
    lastKnownSubtitleLanguage:(nullable NSString *)lastKnownSubtitleLanguage {
  MediaItem* pigeonResult = [[MediaItem alloc] init];
  pigeonResult.url = url;
  pigeonResult.mimeType = mimeType;
  pigeonResult.metadata = metadata;
  pigeonResult.isLive = isLive;
  pigeonResult.playbackStartPositionMs = playbackStartPositionMs;
  pigeonResult.lastKnownAudioLanguage = lastKnownAudioLanguage;
  pigeonResult.lastKnownSubtitleLanguage = lastKnownSubtitleLanguage;
  return pigeonResult;
}
+ (MediaItem *)fromList:(NSArray *)list {
  MediaItem *pigeonResult = [[MediaItem alloc] init];
  pigeonResult.url = GetNullableObjectAtIndex(list, 0);
  pigeonResult.mimeType = GetNullableObjectAtIndex(list, 1);
  pigeonResult.metadata = [MediaMetadata nullableFromList:(GetNullableObjectAtIndex(list, 2))];
  pigeonResult.isLive = GetNullableObjectAtIndex(list, 3);
  pigeonResult.playbackStartPositionMs = GetNullableObjectAtIndex(list, 4);
  pigeonResult.lastKnownAudioLanguage = GetNullableObjectAtIndex(list, 5);
  pigeonResult.lastKnownSubtitleLanguage = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable MediaItem *)nullableFromList:(NSArray *)list {
  return (list) ? [MediaItem fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.url ?: [NSNull null]),
    (self.mimeType ?: [NSNull null]),
    (self.metadata ? [self.metadata toList] : [NSNull null]),
    (self.isLive ?: [NSNull null]),
    (self.playbackStartPositionMs ?: [NSNull null]),
    (self.lastKnownAudioLanguage ?: [NSNull null]),
    (self.lastKnownSubtitleLanguage ?: [NSNull null]),
  ];
}
@end

@implementation MediaMetadata
+ (instancetype)makeWithArtworkUri:(nullable NSString *)artworkUri
    title:(nullable NSString *)title
    artist:(nullable NSString *)artist
    durationMs:(nullable NSNumber *)durationMs
    extras:(nullable NSDictionary<NSString *, id> *)extras {
  MediaMetadata* pigeonResult = [[MediaMetadata alloc] init];
  pigeonResult.artworkUri = artworkUri;
  pigeonResult.title = title;
  pigeonResult.artist = artist;
  pigeonResult.durationMs = durationMs;
  pigeonResult.extras = extras;
  return pigeonResult;
}
+ (MediaMetadata *)fromList:(NSArray *)list {
  MediaMetadata *pigeonResult = [[MediaMetadata alloc] init];
  pigeonResult.artworkUri = GetNullableObjectAtIndex(list, 0);
  pigeonResult.title = GetNullableObjectAtIndex(list, 1);
  pigeonResult.artist = GetNullableObjectAtIndex(list, 2);
  pigeonResult.durationMs = GetNullableObjectAtIndex(list, 3);
  pigeonResult.extras = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable MediaMetadata *)nullableFromList:(NSArray *)list {
  return (list) ? [MediaMetadata fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.artworkUri ?: [NSNull null]),
    (self.title ?: [NSNull null]),
    (self.artist ?: [NSNull null]),
    (self.durationMs ?: [NSNull null]),
    (self.extras ?: [NSNull null]),
  ];
}
@end

@implementation PlayerStateSnapshot
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    playbackState:(PlaybackState)playbackState
    isBuffering:(NSNumber *)isBuffering
    isFullscreen:(NSNumber *)isFullscreen
    playbackSpeed:(NSNumber *)playbackSpeed
    currentMediaItem:(nullable MediaItem *)currentMediaItem
    playbackPositionMs:(nullable NSNumber *)playbackPositionMs {
  PlayerStateSnapshot* pigeonResult = [[PlayerStateSnapshot alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.playbackState = playbackState;
  pigeonResult.isBuffering = isBuffering;
  pigeonResult.isFullscreen = isFullscreen;
  pigeonResult.playbackSpeed = playbackSpeed;
  pigeonResult.currentMediaItem = currentMediaItem;
  pigeonResult.playbackPositionMs = playbackPositionMs;
  return pigeonResult;
}
+ (PlayerStateSnapshot *)fromList:(NSArray *)list {
  PlayerStateSnapshot *pigeonResult = [[PlayerStateSnapshot alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.playerId != nil, @"");
  pigeonResult.playbackState = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.isBuffering = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.isBuffering != nil, @"");
  pigeonResult.isFullscreen = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.isFullscreen != nil, @"");
  pigeonResult.playbackSpeed = GetNullableObjectAtIndex(list, 4);
  NSAssert(pigeonResult.playbackSpeed != nil, @"");
  pigeonResult.currentMediaItem = [MediaItem nullableFromList:(GetNullableObjectAtIndex(list, 5))];
  pigeonResult.playbackPositionMs = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable PlayerStateSnapshot *)nullableFromList:(NSArray *)list {
  return (list) ? [PlayerStateSnapshot fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.playerId ?: [NSNull null]),
    @(self.playbackState),
    (self.isBuffering ?: [NSNull null]),
    (self.isFullscreen ?: [NSNull null]),
    (self.playbackSpeed ?: [NSNull null]),
    (self.currentMediaItem ? [self.currentMediaItem toList] : [NSNull null]),
    (self.playbackPositionMs ?: [NSNull null]),
  ];
}
@end

@implementation ChromecastState
+ (instancetype)makeWithConnectionState:(CastConnectionState)connectionState
    mediaItem:(nullable MediaItem *)mediaItem {
  ChromecastState* pigeonResult = [[ChromecastState alloc] init];
  pigeonResult.connectionState = connectionState;
  pigeonResult.mediaItem = mediaItem;
  return pigeonResult;
}
+ (ChromecastState *)fromList:(NSArray *)list {
  ChromecastState *pigeonResult = [[ChromecastState alloc] init];
  pigeonResult.connectionState = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.mediaItem = [MediaItem nullableFromList:(GetNullableObjectAtIndex(list, 1))];
  return pigeonResult;
}
+ (nullable ChromecastState *)nullableFromList:(NSArray *)list {
  return (list) ? [ChromecastState fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    @(self.connectionState),
    (self.mediaItem ? [self.mediaItem toList] : [NSNull null]),
  ];
}
@end

@implementation PlayerTracksSnapshot
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    audioTracks:(NSArray<Track *> *)audioTracks
    textTracks:(NSArray<Track *> *)textTracks {
  PlayerTracksSnapshot* pigeonResult = [[PlayerTracksSnapshot alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.audioTracks = audioTracks;
  pigeonResult.textTracks = textTracks;
  return pigeonResult;
}
+ (PlayerTracksSnapshot *)fromList:(NSArray *)list {
  PlayerTracksSnapshot *pigeonResult = [[PlayerTracksSnapshot alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.playerId != nil, @"");
  pigeonResult.audioTracks = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.audioTracks != nil, @"");
  pigeonResult.textTracks = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.textTracks != nil, @"");
  return pigeonResult;
}
+ (nullable PlayerTracksSnapshot *)nullableFromList:(NSArray *)list {
  return (list) ? [PlayerTracksSnapshot fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.playerId ?: [NSNull null]),
    (self.audioTracks ?: [NSNull null]),
    (self.textTracks ?: [NSNull null]),
  ];
}
@end

@implementation Track
+ (instancetype)makeWithId:(NSString *)id
    label:(nullable NSString *)label
    language:(nullable NSString *)language
    isSelected:(NSNumber *)isSelected {
  Track* pigeonResult = [[Track alloc] init];
  pigeonResult.id = id;
  pigeonResult.label = label;
  pigeonResult.language = language;
  pigeonResult.isSelected = isSelected;
  return pigeonResult;
}
+ (Track *)fromList:(NSArray *)list {
  Track *pigeonResult = [[Track alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.id != nil, @"");
  pigeonResult.label = GetNullableObjectAtIndex(list, 1);
  pigeonResult.language = GetNullableObjectAtIndex(list, 2);
  pigeonResult.isSelected = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.isSelected != nil, @"");
  return pigeonResult;
}
+ (nullable Track *)nullableFromList:(NSArray *)list {
  return (list) ? [Track fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.id ?: [NSNull null]),
    (self.label ?: [NSNull null]),
    (self.language ?: [NSNull null]),
    (self.isSelected ?: [NSNull null]),
  ];
}
@end

@implementation PrimaryPlayerChangedEvent
+ (instancetype)makeWithPlayerId:(nullable NSString *)playerId {
  PrimaryPlayerChangedEvent* pigeonResult = [[PrimaryPlayerChangedEvent alloc] init];
  pigeonResult.playerId = playerId;
  return pigeonResult;
}
+ (PrimaryPlayerChangedEvent *)fromList:(NSArray *)list {
  PrimaryPlayerChangedEvent *pigeonResult = [[PrimaryPlayerChangedEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  return pigeonResult;
}
+ (nullable PrimaryPlayerChangedEvent *)nullableFromList:(NSArray *)list {
  return (list) ? [PrimaryPlayerChangedEvent fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.playerId ?: [NSNull null]),
  ];
}
@end

@implementation PlayerStateUpdateEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    snapshot:(PlayerStateSnapshot *)snapshot {
  PlayerStateUpdateEvent* pigeonResult = [[PlayerStateUpdateEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.snapshot = snapshot;
  return pigeonResult;
}
+ (PlayerStateUpdateEvent *)fromList:(NSArray *)list {
  PlayerStateUpdateEvent *pigeonResult = [[PlayerStateUpdateEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.playerId != nil, @"");
  pigeonResult.snapshot = [PlayerStateSnapshot nullableFromList:(GetNullableObjectAtIndex(list, 1))];
  NSAssert(pigeonResult.snapshot != nil, @"");
  return pigeonResult;
}
+ (nullable PlayerStateUpdateEvent *)nullableFromList:(NSArray *)list {
  return (list) ? [PlayerStateUpdateEvent fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.playerId ?: [NSNull null]),
    (self.snapshot ? [self.snapshot toList] : [NSNull null]),
  ];
}
@end

@implementation PositionDiscontinuityEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    playbackPositionMs:(nullable NSNumber *)playbackPositionMs {
  PositionDiscontinuityEvent* pigeonResult = [[PositionDiscontinuityEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.playbackPositionMs = playbackPositionMs;
  return pigeonResult;
}
+ (PositionDiscontinuityEvent *)fromList:(NSArray *)list {
  PositionDiscontinuityEvent *pigeonResult = [[PositionDiscontinuityEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.playerId != nil, @"");
  pigeonResult.playbackPositionMs = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable PositionDiscontinuityEvent *)nullableFromList:(NSArray *)list {
  return (list) ? [PositionDiscontinuityEvent fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.playerId ?: [NSNull null]),
    (self.playbackPositionMs ?: [NSNull null]),
  ];
}
@end

@implementation PlaybackStateChangedEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    playbackState:(PlaybackState)playbackState
    isBuffering:(NSNumber *)isBuffering {
  PlaybackStateChangedEvent* pigeonResult = [[PlaybackStateChangedEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.playbackState = playbackState;
  pigeonResult.isBuffering = isBuffering;
  return pigeonResult;
}
+ (PlaybackStateChangedEvent *)fromList:(NSArray *)list {
  PlaybackStateChangedEvent *pigeonResult = [[PlaybackStateChangedEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.playerId != nil, @"");
  pigeonResult.playbackState = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.isBuffering = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.isBuffering != nil, @"");
  return pigeonResult;
}
+ (nullable PlaybackStateChangedEvent *)nullableFromList:(NSArray *)list {
  return (list) ? [PlaybackStateChangedEvent fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.playerId ?: [NSNull null]),
    @(self.playbackState),
    (self.isBuffering ?: [NSNull null]),
  ];
}
@end

@implementation PlaybackEndedEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    mediaItem:(nullable MediaItem *)mediaItem {
  PlaybackEndedEvent* pigeonResult = [[PlaybackEndedEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.mediaItem = mediaItem;
  return pigeonResult;
}
+ (PlaybackEndedEvent *)fromList:(NSArray *)list {
  PlaybackEndedEvent *pigeonResult = [[PlaybackEndedEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.playerId != nil, @"");
  pigeonResult.mediaItem = [MediaItem nullableFromList:(GetNullableObjectAtIndex(list, 1))];
  return pigeonResult;
}
+ (nullable PlaybackEndedEvent *)nullableFromList:(NSArray *)list {
  return (list) ? [PlaybackEndedEvent fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.playerId ?: [NSNull null]),
    (self.mediaItem ? [self.mediaItem toList] : [NSNull null]),
  ];
}
@end

@implementation PictureInPictureModeChangedEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    isInPipMode:(NSNumber *)isInPipMode {
  PictureInPictureModeChangedEvent* pigeonResult = [[PictureInPictureModeChangedEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.isInPipMode = isInPipMode;
  return pigeonResult;
}
+ (PictureInPictureModeChangedEvent *)fromList:(NSArray *)list {
  PictureInPictureModeChangedEvent *pigeonResult = [[PictureInPictureModeChangedEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.playerId != nil, @"");
  pigeonResult.isInPipMode = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.isInPipMode != nil, @"");
  return pigeonResult;
}
+ (nullable PictureInPictureModeChangedEvent *)nullableFromList:(NSArray *)list {
  return (list) ? [PictureInPictureModeChangedEvent fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.playerId ?: [NSNull null]),
    (self.isInPipMode ?: [NSNull null]),
  ];
}
@end

@implementation MediaItemTransitionEvent
+ (instancetype)makeWithPlayerId:(NSString *)playerId
    mediaItem:(nullable MediaItem *)mediaItem {
  MediaItemTransitionEvent* pigeonResult = [[MediaItemTransitionEvent alloc] init];
  pigeonResult.playerId = playerId;
  pigeonResult.mediaItem = mediaItem;
  return pigeonResult;
}
+ (MediaItemTransitionEvent *)fromList:(NSArray *)list {
  MediaItemTransitionEvent *pigeonResult = [[MediaItemTransitionEvent alloc] init];
  pigeonResult.playerId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.playerId != nil, @"");
  pigeonResult.mediaItem = [MediaItem nullableFromList:(GetNullableObjectAtIndex(list, 1))];
  return pigeonResult;
}
+ (nullable MediaItemTransitionEvent *)nullableFromList:(NSArray *)list {
  return (list) ? [MediaItemTransitionEvent fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.playerId ?: [NSNull null]),
    (self.mediaItem ? [self.mediaItem toList] : [NSNull null]),
  ];
}
@end

@interface PlaybackPlatformPigeonCodecReader : FlutterStandardReader
@end
@implementation PlaybackPlatformPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [AppConfig fromList:[self readValue]];
    case 129: 
      return [ChromecastState fromList:[self readValue]];
    case 130: 
      return [MediaItem fromList:[self readValue]];
    case 131: 
      return [MediaMetadata fromList:[self readValue]];
    case 132: 
      return [NpawConfig fromList:[self readValue]];
    case 133: 
      return [PlayerStateSnapshot fromList:[self readValue]];
    case 134: 
      return [PlayerTracksSnapshot fromList:[self readValue]];
    case 135: 
      return [Track fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface PlaybackPlatformPigeonCodecWriter : FlutterStandardWriter
@end
@implementation PlaybackPlatformPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[AppConfig class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ChromecastState class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MediaItem class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MediaMetadata class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[NpawConfig class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlayerStateSnapshot class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlayerTracksSnapshot class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[Track class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface PlaybackPlatformPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PlaybackPlatformPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PlaybackPlatformPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PlaybackPlatformPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *PlaybackPlatformPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    PlaybackPlatformPigeonCodecReaderWriter *readerWriter = [[PlaybackPlatformPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void PlaybackPlatformPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PlaybackPlatformPigeon> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.attach"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(attachWithCompletion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(attachWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api attachWithCompletion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.newPlayer"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(newPlayer:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(newPlayer:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_url = GetNullableObjectAtIndex(args, 0);
        [api newPlayer:arg_url completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.queueMediaItem"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(queueMediaItem:mediaItem:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(queueMediaItem:mediaItem:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        MediaItem *arg_mediaItem = GetNullableObjectAtIndex(args, 1);
        [api queueMediaItem:arg_playerId mediaItem:arg_mediaItem completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.replaceCurrentMediaItem"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(replaceCurrentMediaItem:mediaItem:playbackPositionFromPrimary:autoplay:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(replaceCurrentMediaItem:mediaItem:playbackPositionFromPrimary:autoplay:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        MediaItem *arg_mediaItem = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_playbackPositionFromPrimary = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_autoplay = GetNullableObjectAtIndex(args, 3);
        [api replaceCurrentMediaItem:arg_playerId mediaItem:arg_mediaItem playbackPositionFromPrimary:arg_playbackPositionFromPrimary autoplay:arg_autoplay completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.setPlayerViewVisibility"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPlayerViewVisibility:visible:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setPlayerViewVisibility:visible:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_viewId = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_visible = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api setPlayerViewVisibility:arg_viewId visible:arg_visible error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.setPrimary"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPrimary:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setPrimary:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        [api setPrimary:arg_id completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.play"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(play:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(play:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api play:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.seekTo"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(seek:positionMs:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(seek:positionMs:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_positionMs = GetNullableObjectAtIndex(args, 1);
        [api seek:arg_playerId positionMs:arg_positionMs completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.pause"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pause:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(pause:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api pause:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.stop"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stop:reset:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(stop:reset:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_reset = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api stop:arg_playerId reset:arg_reset error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.setSelectedTrack"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setSelectedTrack:type:trackId:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setSelectedTrack:type:trackId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        TrackType arg_type = [GetNullableObjectAtIndex(args, 1) integerValue];
        NSString *arg_trackId = GetNullableObjectAtIndex(args, 2);
        [api setSelectedTrack:arg_playerId type:arg_type trackId:arg_trackId completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.setPlaybackSpeed"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPlaybackSpeed:speed:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setPlaybackSpeed:speed:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_speed = GetNullableObjectAtIndex(args, 1);
        [api setPlaybackSpeed:arg_playerId speed:arg_speed completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.exitFullscreen"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(exitFullscreen:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(exitFullscreen:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api exitFullscreen:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.enterFullscreen"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(enterFullscreen:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(enterFullscreen:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api enterFullscreen:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.setNpawConfig"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setNpawConfig:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setNpawConfig:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NpawConfig *arg_config = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setNpawConfig:arg_config error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.setAppConfig"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setAppConfig:error:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(setAppConfig:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        AppConfig *arg_config = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api setAppConfig:arg_config error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.getTracks"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getTracks:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(getTracks:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        [api getTracks:arg_playerId completion:^(PlayerTracksSnapshot *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.getPlayerState"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getPlayerState:completion:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(getPlayerState:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_playerId = GetNullableObjectAtIndex(args, 0);
        [api getPlayerState:arg_playerId completion:^(PlayerStateSnapshot *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.getChromecastState"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getChromecastState:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(getChromecastState:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getChromecastState:^(ChromecastState *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.openExpandedCastController"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(openExpandedCastController:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(openExpandedCastController:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api openExpandedCastController:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PlaybackPlatformPigeon.openCastDialog"
        binaryMessenger:binaryMessenger
        codec:PlaybackPlatformPigeonGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(openCastDialog:)], @"PlaybackPlatformPigeon api (%@) doesn't respond to @selector(openCastDialog:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api openCastDialog:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface PlaybackListenerPigeonCodecReader : FlutterStandardReader
@end
@implementation PlaybackListenerPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [MediaItem fromList:[self readValue]];
    case 129: 
      return [MediaItemTransitionEvent fromList:[self readValue]];
    case 130: 
      return [MediaMetadata fromList:[self readValue]];
    case 131: 
      return [PictureInPictureModeChangedEvent fromList:[self readValue]];
    case 132: 
      return [PlaybackEndedEvent fromList:[self readValue]];
    case 133: 
      return [PlaybackStateChangedEvent fromList:[self readValue]];
    case 134: 
      return [PlayerStateSnapshot fromList:[self readValue]];
    case 135: 
      return [PlayerStateUpdateEvent fromList:[self readValue]];
    case 136: 
      return [PositionDiscontinuityEvent fromList:[self readValue]];
    case 137: 
      return [PrimaryPlayerChangedEvent fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface PlaybackListenerPigeonCodecWriter : FlutterStandardWriter
@end
@implementation PlaybackListenerPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[MediaItem class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MediaItemTransitionEvent class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[MediaMetadata class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PictureInPictureModeChangedEvent class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlaybackEndedEvent class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlaybackStateChangedEvent class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlayerStateSnapshot class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PlayerStateUpdateEvent class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PositionDiscontinuityEvent class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PrimaryPlayerChangedEvent class]]) {
    [self writeByte:137];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface PlaybackListenerPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PlaybackListenerPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PlaybackListenerPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PlaybackListenerPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *PlaybackListenerPigeonGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    PlaybackListenerPigeonCodecReaderWriter *readerWriter = [[PlaybackListenerPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface PlaybackListenerPigeon ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation PlaybackListenerPigeon

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onPrimaryPlayerChanged:(PrimaryPlayerChangedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.PlaybackListenerPigeon.onPrimaryPlayerChanged"
      binaryMessenger:self.binaryMessenger
      codec:PlaybackListenerPigeonGetCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onPositionDiscontinuity:(PositionDiscontinuityEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.PlaybackListenerPigeon.onPositionDiscontinuity"
      binaryMessenger:self.binaryMessenger
      codec:PlaybackListenerPigeonGetCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onPlayerStateUpdate:(PlayerStateUpdateEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.PlaybackListenerPigeon.onPlayerStateUpdate"
      binaryMessenger:self.binaryMessenger
      codec:PlaybackListenerPigeonGetCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onPlaybackStateChanged:(PlaybackStateChangedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.PlaybackListenerPigeon.onPlaybackStateChanged"
      binaryMessenger:self.binaryMessenger
      codec:PlaybackListenerPigeonGetCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onPlaybackEnded:(PlaybackEndedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.PlaybackListenerPigeon.onPlaybackEnded"
      binaryMessenger:self.binaryMessenger
      codec:PlaybackListenerPigeonGetCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onMediaItemTransition:(MediaItemTransitionEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.PlaybackListenerPigeon.onMediaItemTransition"
      binaryMessenger:self.binaryMessenger
      codec:PlaybackListenerPigeonGetCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
- (void)onPictureInPictureModeChanged:(PictureInPictureModeChangedEvent *)arg_event completion:(void (^)(FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.PlaybackListenerPigeon.onPictureInPictureModeChanged"
      binaryMessenger:self.binaryMessenger
      codec:PlaybackListenerPigeonGetCodec()];
  [channel sendMessage:@[arg_event ?: [NSNull null]] reply:^(id reply) {
    completion(nil);
  }];
}
@end

