import 'package:freezed_annotation/freezed_annotation.dart';

part 'feature_flags.freezed.dart';
part 'feature_flags.g.dart';

@freezed
sealed class FeatureFlags with _$FeatureFlags {
  const FeatureFlags._();

  const factory FeatureFlags({
    required List<String> variants,
    required bool auth,
    required bool publicSignup,
    required bool socialSignup,
    required bool autoplayNext,
    required bool shareVideoButton,
    required bool flutterPlayerControls,
    required bool playNextButton,
    required bool chapters,
    required bool chaptersFirstTab,
    required bool download,
    required bool shorts,
    required bool shortsSourceButtonPrimary,
    required bool shortsSharing,
    required bool shortsHideAutoGenerated,
    required bool shortsHideBeta,
    required bool shortsGuide,
    required bool linkToBccLive,
    required bool forceBccLive,
    required bool removeLiveTab,
    required bool disableNpawShorts,
  }) = _FeatureFlags;

  factory FeatureFlags.fromJson(Map<String, dynamic> json) => _$FeatureFlagsFromJson(json);
}
