// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'feature_flags.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#adding-getters-and-methods-to-our-models');

/// @nodoc
mixin _$FeatureFlags {
  Map<String, ToggleConfig> get toggles => throw _privateConstructorUsedError;
  bool get auth => throw _privateConstructorUsedError;
  bool get publicSignup => throw _privateConstructorUsedError;
  bool get socialSignup => throw _privateConstructorUsedError;
  bool get autoplayNext => throw _privateConstructorUsedError;
  bool get shareVideoButton => throw _privateConstructorUsedError;
  bool get flutterPlayerControls => throw _privateConstructorUsedError;
  bool get playNextButton => throw _privateConstructorUsedError;
  bool get chapters => throw _privateConstructorUsedError;
  bool get chaptersFirstTab => throw _privateConstructorUsedError;
  bool get download => throw _privateConstructorUsedError;
  bool get shorts => throw _privateConstructorUsedError;
  bool get shortsSourceButtonPrimary => throw _privateConstructorUsedError;
  bool get shortsSharing => throw _privateConstructorUsedError;
  bool get shortsHideAutoGenerated => throw _privateConstructorUsedError;
  bool get shortsHideBeta => throw _privateConstructorUsedError;
  bool get shortsGuide => throw _privateConstructorUsedError;
  bool get linkToBccLive => throw _privateConstructorUsedError;
  bool get forceBccLive => throw _privateConstructorUsedError;
  bool get removeLiveTab => throw _privateConstructorUsedError;
  bool get disableNpawShorts => throw _privateConstructorUsedError;

  @JsonKey(ignore: true)
  $FeatureFlagsCopyWith<FeatureFlags> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $FeatureFlagsCopyWith<$Res> {
  factory $FeatureFlagsCopyWith(
          FeatureFlags value, $Res Function(FeatureFlags) then) =
      _$FeatureFlagsCopyWithImpl<$Res, FeatureFlags>;
  @useResult
  $Res call(
      {Map<String, ToggleConfig> toggles,
      bool auth,
      bool publicSignup,
      bool socialSignup,
      bool autoplayNext,
      bool shareVideoButton,
      bool flutterPlayerControls,
      bool playNextButton,
      bool chapters,
      bool chaptersFirstTab,
      bool download,
      bool shorts,
      bool shortsSourceButtonPrimary,
      bool shortsSharing,
      bool shortsHideAutoGenerated,
      bool shortsHideBeta,
      bool shortsGuide,
      bool linkToBccLive,
      bool forceBccLive,
      bool removeLiveTab,
      bool disableNpawShorts});
}

/// @nodoc
class _$FeatureFlagsCopyWithImpl<$Res, $Val extends FeatureFlags>
    implements $FeatureFlagsCopyWith<$Res> {
  _$FeatureFlagsCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? toggles = null,
    Object? auth = null,
    Object? publicSignup = null,
    Object? socialSignup = null,
    Object? autoplayNext = null,
    Object? shareVideoButton = null,
    Object? flutterPlayerControls = null,
    Object? playNextButton = null,
    Object? chapters = null,
    Object? chaptersFirstTab = null,
    Object? download = null,
    Object? shorts = null,
    Object? shortsSourceButtonPrimary = null,
    Object? shortsSharing = null,
    Object? shortsHideAutoGenerated = null,
    Object? shortsHideBeta = null,
    Object? shortsGuide = null,
    Object? linkToBccLive = null,
    Object? forceBccLive = null,
    Object? removeLiveTab = null,
    Object? disableNpawShorts = null,
  }) {
    return _then(_value.copyWith(
      toggles: null == toggles
          ? _value.toggles
          : toggles // ignore: cast_nullable_to_non_nullable
              as Map<String, ToggleConfig>,
      auth: null == auth
          ? _value.auth
          : auth // ignore: cast_nullable_to_non_nullable
              as bool,
      publicSignup: null == publicSignup
          ? _value.publicSignup
          : publicSignup // ignore: cast_nullable_to_non_nullable
              as bool,
      socialSignup: null == socialSignup
          ? _value.socialSignup
          : socialSignup // ignore: cast_nullable_to_non_nullable
              as bool,
      autoplayNext: null == autoplayNext
          ? _value.autoplayNext
          : autoplayNext // ignore: cast_nullable_to_non_nullable
              as bool,
      shareVideoButton: null == shareVideoButton
          ? _value.shareVideoButton
          : shareVideoButton // ignore: cast_nullable_to_non_nullable
              as bool,
      flutterPlayerControls: null == flutterPlayerControls
          ? _value.flutterPlayerControls
          : flutterPlayerControls // ignore: cast_nullable_to_non_nullable
              as bool,
      playNextButton: null == playNextButton
          ? _value.playNextButton
          : playNextButton // ignore: cast_nullable_to_non_nullable
              as bool,
      chapters: null == chapters
          ? _value.chapters
          : chapters // ignore: cast_nullable_to_non_nullable
              as bool,
      chaptersFirstTab: null == chaptersFirstTab
          ? _value.chaptersFirstTab
          : chaptersFirstTab // ignore: cast_nullable_to_non_nullable
              as bool,
      download: null == download
          ? _value.download
          : download // ignore: cast_nullable_to_non_nullable
              as bool,
      shorts: null == shorts
          ? _value.shorts
          : shorts // ignore: cast_nullable_to_non_nullable
              as bool,
      shortsSourceButtonPrimary: null == shortsSourceButtonPrimary
          ? _value.shortsSourceButtonPrimary
          : shortsSourceButtonPrimary // ignore: cast_nullable_to_non_nullable
              as bool,
      shortsSharing: null == shortsSharing
          ? _value.shortsSharing
          : shortsSharing // ignore: cast_nullable_to_non_nullable
              as bool,
      shortsHideAutoGenerated: null == shortsHideAutoGenerated
          ? _value.shortsHideAutoGenerated
          : shortsHideAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
      shortsHideBeta: null == shortsHideBeta
          ? _value.shortsHideBeta
          : shortsHideBeta // ignore: cast_nullable_to_non_nullable
              as bool,
      shortsGuide: null == shortsGuide
          ? _value.shortsGuide
          : shortsGuide // ignore: cast_nullable_to_non_nullable
              as bool,
      linkToBccLive: null == linkToBccLive
          ? _value.linkToBccLive
          : linkToBccLive // ignore: cast_nullable_to_non_nullable
              as bool,
      forceBccLive: null == forceBccLive
          ? _value.forceBccLive
          : forceBccLive // ignore: cast_nullable_to_non_nullable
              as bool,
      removeLiveTab: null == removeLiveTab
          ? _value.removeLiveTab
          : removeLiveTab // ignore: cast_nullable_to_non_nullable
              as bool,
      disableNpawShorts: null == disableNpawShorts
          ? _value.disableNpawShorts
          : disableNpawShorts // ignore: cast_nullable_to_non_nullable
              as bool,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$FeatureFlagsImplCopyWith<$Res>
    implements $FeatureFlagsCopyWith<$Res> {
  factory _$$FeatureFlagsImplCopyWith(
          _$FeatureFlagsImpl value, $Res Function(_$FeatureFlagsImpl) then) =
      __$$FeatureFlagsImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {Map<String, ToggleConfig> toggles,
      bool auth,
      bool publicSignup,
      bool socialSignup,
      bool autoplayNext,
      bool shareVideoButton,
      bool flutterPlayerControls,
      bool playNextButton,
      bool chapters,
      bool chaptersFirstTab,
      bool download,
      bool shorts,
      bool shortsSourceButtonPrimary,
      bool shortsSharing,
      bool shortsHideAutoGenerated,
      bool shortsHideBeta,
      bool shortsGuide,
      bool linkToBccLive,
      bool forceBccLive,
      bool removeLiveTab,
      bool disableNpawShorts});
}

/// @nodoc
class __$$FeatureFlagsImplCopyWithImpl<$Res>
    extends _$FeatureFlagsCopyWithImpl<$Res, _$FeatureFlagsImpl>
    implements _$$FeatureFlagsImplCopyWith<$Res> {
  __$$FeatureFlagsImplCopyWithImpl(
      _$FeatureFlagsImpl _value, $Res Function(_$FeatureFlagsImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? toggles = null,
    Object? auth = null,
    Object? publicSignup = null,
    Object? socialSignup = null,
    Object? autoplayNext = null,
    Object? shareVideoButton = null,
    Object? flutterPlayerControls = null,
    Object? playNextButton = null,
    Object? chapters = null,
    Object? chaptersFirstTab = null,
    Object? download = null,
    Object? shorts = null,
    Object? shortsSourceButtonPrimary = null,
    Object? shortsSharing = null,
    Object? shortsHideAutoGenerated = null,
    Object? shortsHideBeta = null,
    Object? shortsGuide = null,
    Object? linkToBccLive = null,
    Object? forceBccLive = null,
    Object? removeLiveTab = null,
    Object? disableNpawShorts = null,
  }) {
    return _then(_$FeatureFlagsImpl(
      toggles: null == toggles
          ? _value._toggles
          : toggles // ignore: cast_nullable_to_non_nullable
              as Map<String, ToggleConfig>,
      auth: null == auth
          ? _value.auth
          : auth // ignore: cast_nullable_to_non_nullable
              as bool,
      publicSignup: null == publicSignup
          ? _value.publicSignup
          : publicSignup // ignore: cast_nullable_to_non_nullable
              as bool,
      socialSignup: null == socialSignup
          ? _value.socialSignup
          : socialSignup // ignore: cast_nullable_to_non_nullable
              as bool,
      autoplayNext: null == autoplayNext
          ? _value.autoplayNext
          : autoplayNext // ignore: cast_nullable_to_non_nullable
              as bool,
      shareVideoButton: null == shareVideoButton
          ? _value.shareVideoButton
          : shareVideoButton // ignore: cast_nullable_to_non_nullable
              as bool,
      flutterPlayerControls: null == flutterPlayerControls
          ? _value.flutterPlayerControls
          : flutterPlayerControls // ignore: cast_nullable_to_non_nullable
              as bool,
      playNextButton: null == playNextButton
          ? _value.playNextButton
          : playNextButton // ignore: cast_nullable_to_non_nullable
              as bool,
      chapters: null == chapters
          ? _value.chapters
          : chapters // ignore: cast_nullable_to_non_nullable
              as bool,
      chaptersFirstTab: null == chaptersFirstTab
          ? _value.chaptersFirstTab
          : chaptersFirstTab // ignore: cast_nullable_to_non_nullable
              as bool,
      download: null == download
          ? _value.download
          : download // ignore: cast_nullable_to_non_nullable
              as bool,
      shorts: null == shorts
          ? _value.shorts
          : shorts // ignore: cast_nullable_to_non_nullable
              as bool,
      shortsSourceButtonPrimary: null == shortsSourceButtonPrimary
          ? _value.shortsSourceButtonPrimary
          : shortsSourceButtonPrimary // ignore: cast_nullable_to_non_nullable
              as bool,
      shortsSharing: null == shortsSharing
          ? _value.shortsSharing
          : shortsSharing // ignore: cast_nullable_to_non_nullable
              as bool,
      shortsHideAutoGenerated: null == shortsHideAutoGenerated
          ? _value.shortsHideAutoGenerated
          : shortsHideAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
      shortsHideBeta: null == shortsHideBeta
          ? _value.shortsHideBeta
          : shortsHideBeta // ignore: cast_nullable_to_non_nullable
              as bool,
      shortsGuide: null == shortsGuide
          ? _value.shortsGuide
          : shortsGuide // ignore: cast_nullable_to_non_nullable
              as bool,
      linkToBccLive: null == linkToBccLive
          ? _value.linkToBccLive
          : linkToBccLive // ignore: cast_nullable_to_non_nullable
              as bool,
      forceBccLive: null == forceBccLive
          ? _value.forceBccLive
          : forceBccLive // ignore: cast_nullable_to_non_nullable
              as bool,
      removeLiveTab: null == removeLiveTab
          ? _value.removeLiveTab
          : removeLiveTab // ignore: cast_nullable_to_non_nullable
              as bool,
      disableNpawShorts: null == disableNpawShorts
          ? _value.disableNpawShorts
          : disableNpawShorts // ignore: cast_nullable_to_non_nullable
              as bool,
    ));
  }
}

/// @nodoc

class _$FeatureFlagsImpl extends _FeatureFlags {
  const _$FeatureFlagsImpl(
      {final Map<String, ToggleConfig> toggles = const {},
      this.auth = true,
      this.publicSignup = false,
      this.socialSignup = false,
      this.autoplayNext = false,
      this.shareVideoButton = true,
      this.flutterPlayerControls = false,
      this.playNextButton = false,
      this.chapters = false,
      this.chaptersFirstTab = false,
      this.download = false,
      this.shorts = false,
      this.shortsSourceButtonPrimary = false,
      this.shortsSharing = false,
      this.shortsHideAutoGenerated = false,
      this.shortsHideBeta = false,
      this.shortsGuide = false,
      this.linkToBccLive = true,
      this.forceBccLive = true,
      this.removeLiveTab = true,
      this.disableNpawShorts = false})
      : _toggles = toggles,
        super._();

  final Map<String, ToggleConfig> _toggles;
  @override
  @JsonKey()
  Map<String, ToggleConfig> get toggles {
    if (_toggles is EqualUnmodifiableMapView) return _toggles;
    // ignore: implicit_dynamic_type
    return EqualUnmodifiableMapView(_toggles);
  }

  @override
  @JsonKey()
  final bool auth;
  @override
  @JsonKey()
  final bool publicSignup;
  @override
  @JsonKey()
  final bool socialSignup;
  @override
  @JsonKey()
  final bool autoplayNext;
  @override
  @JsonKey()
  final bool shareVideoButton;
  @override
  @JsonKey()
  final bool flutterPlayerControls;
  @override
  @JsonKey()
  final bool playNextButton;
  @override
  @JsonKey()
  final bool chapters;
  @override
  @JsonKey()
  final bool chaptersFirstTab;
  @override
  @JsonKey()
  final bool download;
  @override
  @JsonKey()
  final bool shorts;
  @override
  @JsonKey()
  final bool shortsSourceButtonPrimary;
  @override
  @JsonKey()
  final bool shortsSharing;
  @override
  @JsonKey()
  final bool shortsHideAutoGenerated;
  @override
  @JsonKey()
  final bool shortsHideBeta;
  @override
  @JsonKey()
  final bool shortsGuide;
  @override
  @JsonKey()
  final bool linkToBccLive;
  @override
  @JsonKey()
  final bool forceBccLive;
  @override
  @JsonKey()
  final bool removeLiveTab;
  @override
  @JsonKey()
  final bool disableNpawShorts;

  @override
  String toString() {
    return 'FeatureFlags(toggles: $toggles, auth: $auth, publicSignup: $publicSignup, socialSignup: $socialSignup, autoplayNext: $autoplayNext, shareVideoButton: $shareVideoButton, flutterPlayerControls: $flutterPlayerControls, playNextButton: $playNextButton, chapters: $chapters, chaptersFirstTab: $chaptersFirstTab, download: $download, shorts: $shorts, shortsSourceButtonPrimary: $shortsSourceButtonPrimary, shortsSharing: $shortsSharing, shortsHideAutoGenerated: $shortsHideAutoGenerated, shortsHideBeta: $shortsHideBeta, shortsGuide: $shortsGuide, linkToBccLive: $linkToBccLive, forceBccLive: $forceBccLive, removeLiveTab: $removeLiveTab, disableNpawShorts: $disableNpawShorts)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$FeatureFlagsImpl &&
            const DeepCollectionEquality().equals(other._toggles, _toggles) &&
            (identical(other.auth, auth) || other.auth == auth) &&
            (identical(other.publicSignup, publicSignup) ||
                other.publicSignup == publicSignup) &&
            (identical(other.socialSignup, socialSignup) ||
                other.socialSignup == socialSignup) &&
            (identical(other.autoplayNext, autoplayNext) ||
                other.autoplayNext == autoplayNext) &&
            (identical(other.shareVideoButton, shareVideoButton) ||
                other.shareVideoButton == shareVideoButton) &&
            (identical(other.flutterPlayerControls, flutterPlayerControls) ||
                other.flutterPlayerControls == flutterPlayerControls) &&
            (identical(other.playNextButton, playNextButton) ||
                other.playNextButton == playNextButton) &&
            (identical(other.chapters, chapters) ||
                other.chapters == chapters) &&
            (identical(other.chaptersFirstTab, chaptersFirstTab) ||
                other.chaptersFirstTab == chaptersFirstTab) &&
            (identical(other.download, download) ||
                other.download == download) &&
            (identical(other.shorts, shorts) || other.shorts == shorts) &&
            (identical(other.shortsSourceButtonPrimary,
                    shortsSourceButtonPrimary) ||
                other.shortsSourceButtonPrimary == shortsSourceButtonPrimary) &&
            (identical(other.shortsSharing, shortsSharing) ||
                other.shortsSharing == shortsSharing) &&
            (identical(
                    other.shortsHideAutoGenerated, shortsHideAutoGenerated) ||
                other.shortsHideAutoGenerated == shortsHideAutoGenerated) &&
            (identical(other.shortsHideBeta, shortsHideBeta) ||
                other.shortsHideBeta == shortsHideBeta) &&
            (identical(other.shortsGuide, shortsGuide) ||
                other.shortsGuide == shortsGuide) &&
            (identical(other.linkToBccLive, linkToBccLive) ||
                other.linkToBccLive == linkToBccLive) &&
            (identical(other.forceBccLive, forceBccLive) ||
                other.forceBccLive == forceBccLive) &&
            (identical(other.removeLiveTab, removeLiveTab) ||
                other.removeLiveTab == removeLiveTab) &&
            (identical(other.disableNpawShorts, disableNpawShorts) ||
                other.disableNpawShorts == disableNpawShorts));
  }

  @override
  int get hashCode => Object.hashAll([
        runtimeType,
        const DeepCollectionEquality().hash(_toggles),
        auth,
        publicSignup,
        socialSignup,
        autoplayNext,
        shareVideoButton,
        flutterPlayerControls,
        playNextButton,
        chapters,
        chaptersFirstTab,
        download,
        shorts,
        shortsSourceButtonPrimary,
        shortsSharing,
        shortsHideAutoGenerated,
        shortsHideBeta,
        shortsGuide,
        linkToBccLive,
        forceBccLive,
        removeLiveTab,
        disableNpawShorts
      ]);

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$FeatureFlagsImplCopyWith<_$FeatureFlagsImpl> get copyWith =>
      __$$FeatureFlagsImplCopyWithImpl<_$FeatureFlagsImpl>(this, _$identity);
}

abstract class _FeatureFlags extends FeatureFlags {
  const factory _FeatureFlags(
      {final Map<String, ToggleConfig> toggles,
      final bool auth,
      final bool publicSignup,
      final bool socialSignup,
      final bool autoplayNext,
      final bool shareVideoButton,
      final bool flutterPlayerControls,
      final bool playNextButton,
      final bool chapters,
      final bool chaptersFirstTab,
      final bool download,
      final bool shorts,
      final bool shortsSourceButtonPrimary,
      final bool shortsSharing,
      final bool shortsHideAutoGenerated,
      final bool shortsHideBeta,
      final bool shortsGuide,
      final bool linkToBccLive,
      final bool forceBccLive,
      final bool removeLiveTab,
      final bool disableNpawShorts}) = _$FeatureFlagsImpl;
  const _FeatureFlags._() : super._();

  @override
  Map<String, ToggleConfig> get toggles;
  @override
  bool get auth;
  @override
  bool get publicSignup;
  @override
  bool get socialSignup;
  @override
  bool get autoplayNext;
  @override
  bool get shareVideoButton;
  @override
  bool get flutterPlayerControls;
  @override
  bool get playNextButton;
  @override
  bool get chapters;
  @override
  bool get chaptersFirstTab;
  @override
  bool get download;
  @override
  bool get shorts;
  @override
  bool get shortsSourceButtonPrimary;
  @override
  bool get shortsSharing;
  @override
  bool get shortsHideAutoGenerated;
  @override
  bool get shortsHideBeta;
  @override
  bool get shortsGuide;
  @override
  bool get linkToBccLive;
  @override
  bool get forceBccLive;
  @override
  bool get removeLiveTab;
  @override
  bool get disableNpawShorts;
  @override
  @JsonKey(ignore: true)
  _$$FeatureFlagsImplCopyWith<_$FeatureFlagsImpl> get copyWith =>
      throw _privateConstructorUsedError;
}
