// Autogenerated from Pigeon (v3.2.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by PlaybackServicePigeon.
NSObject<FlutterMessageCodec> *PlaybackServicePigeonGetCodec(void);

@protocol PlaybackServicePigeon
- (void)newPlayerUrl:(nullable NSString *)url completion:(void(^)(NSString *_Nullable, FlutterError *_Nullable))completion;
@end

extern void PlaybackServicePigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PlaybackServicePigeon> *_Nullable api);

NS_ASSUME_NONNULL_END
