// Autogenerated from Pigeon (v3.2.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class PositionUpdateEvent;

@interface PositionUpdateEvent : NSObject
+ (instancetype)makeWithPlaybackPositionMs:(nullable NSNumber *)playbackPositionMs;
@property(nonatomic, strong, nullable) NSNumber * playbackPositionMs;
@end

/// The codec used by PlaybackListenerPigeon.
NSObject<FlutterMessageCodec> *PlaybackListenerPigeonGetCodec(void);

@interface PlaybackListenerPigeon : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onPositionUpdate:(PositionUpdateEvent *)event completion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
