// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeHQZV2K_sJ6iAgK9YfiEn0lfswnMKWHk',
    appId: '1:459822980184:web:4f4b3ec1f913943a4efe2d',
    messagingSenderId: '459822980184',
    projectId: 'bcc-media-test',
    authDomain: 'bcc-media-test.firebaseapp.com',
    storageBucket: 'bcc-media-test.appspot.com',
    measurementId: 'G-385FC6FYFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfLOJ4j-39lPecPyv0h4j-FB8NMY-zXA',
    appId: '1:459822980184:android:cd8465ea983f8fad4efe2d',
    messagingSenderId: '459822980184',
    projectId: 'bcc-media-test',
    storageBucket: 'bcc-media-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFLWpDkch9VbHVf7hMzw2ElDwn1K59VKs',
    appId: '1:459822980184:ios:54ca766b4f071c554efe2d',
    messagingSenderId: '459822980184',
    projectId: 'bcc-media-test',
    storageBucket: 'bcc-media-test.appspot.com',
    iosClientId: '459822980184-8baat8ca3mkaqbt9253bduibf98cmrl9.apps.googleusercontent.com',
    iosBundleId: 'tv.brunstad.app',
  );
}
